### PR TITLE
Ehren changes

### PR DESCRIPTION
**Pull request by ecollins27**
Login - added login.html with a form for username and password.  Both are used to SSH into citadel.cif.rochester.edu.  The username is saved for log purposes and the password is never used again

Page count - Before the print command is run, checks are done to ensure syntax is correct, all files are pdfs, and the print job is within accepted limits.  The page count is calculated by parsePages which returns the number of pages specified by the user.

Logging - The log was slightly altered to remove unnecessary information.  Copies, pages per page, and orientation now only appear in the log if their values are anything other than default 1 copy, 1 page per page, and portrait orientation.  Files are also saved to file storage, currently called FILE_STORE.  Each saved file is prefixed with the time and date of attempted print.  Everytime a print is attempted, file storage is updated and each file with prefixed with a time over FILE_SAVE_TIME old is deleted.

### CODE REVIEW

**Comment by fenwaypowers** [comment]
Requested changes:

- README Changes
  
  - A "Quick Start" section should be added to the readme, as seen in other CIF repos like [GateKeeper](https://github.com/CIF-Rochester/GateKeeper).
  
  - This text in the `# Website` section should be removed. Stuff like this can be put into pull requests or release notes, but please refrain from using personal pronouns in READMEs.
    
    | I have no prior experience with frontend or web dev. As such all HTML and CSS present is self-taught and by no means final. Should the website or layout of the HTML files disgust some future tech director, feel free to rework it to your liking. |
    | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |

- add the `.idea` folder to the gitignore.
  
  - to ensure the `.idea` folder is deleted from the repository, you may need to:
    - delete the `.idea` folder from your computer (back it up if you like)
    - add `.idea` to the gitignore
    - commit (it's ok if this one change is the whole commit)
    - then you can add back the `.idea` folder. 
  - It should no longer be tracked in the repository after that.

- Add back in config files
  
  - variables such as `UPLOAD_FOLDER`, `PRINTER_NAME`, `MAX_PAGES`, `FILE_SAVE_TIME` should not be hardcoded. These should be stored in a config file like `config.cfg`, and should be loaded into the program by a `config.py` file that uses python's [configparser](https://docs.python.org/3/library/configparser.html) library. Also, the file location for the logger should be in the `config.cfg` as well. 
  - For examples, please see other CIF Python repos such as [GateKeeper](https://github.com/CIF-Rochester/GateKeeper) and [NauticockBot](https://github.com/CIF-Rochester/NauticockBot).

- Command Line Arguments 
  
  - I know it may seem unecessary to do so, but I'd like you to add command line arguments using python's [argparse](https://docs.python.org/3/library/argparse.html) library. All you would need to add is the optional argument to specify a path to the configuration file. An example of this is in the [NauticockBot](https://github.com/CIF-Rochester/NauticockBot)'s command line arguments.
  - Command line arguments section should be added to the readme like in the [NauticockBot](https://github.com/CIF-Rochester/NauticockBot)'s readme.

**Comment by ecollins27** [comment]
Done
config.example.cfg added.  It has 5 variables, logging.log_path, logging.file_storage_path, logging.file_storage_time, printer.printer_name, and print_limitations.max_pages.  Config.py was implemented identically to config.py found in the GateKeeper repo
Also implemented command line with argparser.  The only parameter is an optional custom config path

**Comment by fenwaypowers** [comment]
### Requested Changes

1. **Add `.pycache` to `.gitignore`**
  
  - Ensure that the `.gitignore` file includes an entry for `__pycache__*` to prevent Python bytecode files from being tracked in the repository.
2. **Modify `retCodes.append(ret)`**
  
  - change to `retCodes.append(ret.returncode)`
3. **Update the README**
  
  - Replace the reference to `main.py` in the README with `app.py` to reflect the correct filename.
4. **Fix `PYPDF2` Error**
  
  - Resolve the issue with `PYPDF2` when it attempts to read the number of pages in a PDF.
    
  - Replace the current implementation with the following function:
    
    ```python
    def getNumberOfPage(pdfFile):
        t = subprocess.run(f"pdfinfo {pdfFile}  | awk '/^Pages:/ {{print $2}}'", shell=True, stdout=subprocess.PIPE)
        v = t.stdout.strip()
        try:
            v = v.decode()
        except (UnicodeDecodeError, AttributeError):
            pass
        return v
    ```
    
  - Note: This function is from the [[Web-Printer repository](https://github.com/Koushikphy/Web-Printer)](https://github.com/Koushikphy/Web-Printer).
    
5. **Double-Check Logger Functionality**
  
  - Verify that the logger works as expected, even when a print job fails. Ensure that appropriate log messages are recorded in all scenarios.
6. **Credit Original Source**
  
  - Add attribution to [https://github.com/Koushikphy/Web-Printer](https://github.com/Koushikphy/Web-Printer) in the repository, as much of the code is derived from this project. Include the credit in the README.md.

**Comment by fenwaypowers** [comment]
format the logger to include `levelname`.

the format shouldbe: time, then levelname then message.

**Pull request merged**
